version: 2
checks:
  method-complexity:
    config:
      threshold: 10
plugins:
  brakeman:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-74
  bundler-audit:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
        - python
        - php
  eslint:
    enabled: true
    channel: eslint-5
    config:
      config: .eslintrc.json
      extensions:
        - .js
        - .jsx
  fixme:
    enabled: true
exclude_patterns:
  - config/**/*
  - db/**/*
  - spec/**/*
  - vendor/**/*
  - "**/__generated__/**/*"
