inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-performance
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_sql
    - find_by_full_name
