language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1
before_script:
  - "bin/rake db:create db:test:prepare"
script: bin/rspec
env:
  global:
    - CODY_GITHUB_ACCESS_TOKEN=abc123
    - CODY_GITHUB_REPO=aergonaut/testrepo
branches:
  only:
    - master
