language: ruby
dist: trusty
cache:
  - bundler
  - yarn
rvm:
  - 2.6.4
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - gem install bundler -v '1.17.2'
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
script:
  - script/ci
after_script:
  - if [ "$SUITE" = "yarn" ]; then bin/yarn codecov; fi
env:
  matrix:
    - SUITE=rspec
    - SUITE=yarn
    - SUITE=browser
  global:
    - CODY_GITHUB_ACCESS_TOKEN=abc123
    - CODY_JWT_SECRET_KEY=fake
    - CODY_GITHUB_REPO=aergonaut/testrepo
    - CODY_HOST=cody.example
    - CODY_ATTR_ENCRYPTED_KEY="eTJIFMy/H5/FL2HXllaCyZ5XcY6FsC0itYVN7ZbNxv0="
branches:
  only:
    - master
addons:
  postgresql: "9.4"
  chrome: stable
  apt:
    update: true
    packages:
      - chromium-chromedriver
